Repository ArkEcosystem/laravel-hermes, pull requests merged in 2021-03, with the labels that each got.

#18 refactor: prevent adding duplicate order by clauses
  .gitignore
  src/Models/Concerns/HasNotifications.php
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#17 refactor: update the manage notifications to match design
  resources/views/components/manage-notifications.blade.php
  src/Components/ManageNotifications.php
Labels: Complexity: Medium, Type: Task

#21 refactor: mark all as read button, and chevron open state
  resources/views/components/manage-notifications.blade.php
  src/Components/ManageNotifications.php
Labels: Complexity: Low, Type: Task

#24 feat: handle custom logo types on the notifications views
  resources/views/components/manage-notifications.blade.php
  resources/views/navbar-notifications.blade.php
  resources/views/notification-icon.blade.php
  src/Models/DatabaseNotification.php
Labels: Complexity: Low, Type: Feature

#25 feat: make notifications relatable morphable models
  EXAMPLES.md
  database/migrations/2020_11_17_000000_create_notifications_table.php
  resources/views/components/manage-notifications.blade.php
  resources/views/navbar-notifications.blade.php
  resources/views/notification-icon.blade.php
  src/Contracts/HasNotificationLogo.php
  src/Models/DatabaseNotification.php
Labels: Complexity: Medium, Type: Feature

#28 fix: truncate long titles and use full width for notifications dropdown
  resources/views/navbar-notifications.blade.php
Labels: Complexity: Low, Type: Task
